name: all_printer
description: A new Flutter project.
version: 0.0.1
homepage: https://github.com/taghassan54/all_printer
environment: {sdk: '>=2.17.5 <3.0.0', flutter: '>=2.5.0'}
dependencies:
  flutter: {sdk: flutter}
  plugin_platform_interface: ^2.0.2
  permission_handler: ^10.0.2
  logger: ^1.1.0
  path_provider: ^2.0.11
  dio: ^4.0.6


dev_dependencies:
  flutter_test: {sdk: flutter}
  flutter_lints: ^2.0.0
flutter:
  plugin:
    platforms:
      android: {package: com.example.all_printer, pluginClass: AllPrinterPlugin}
      ios: {pluginClass: AllPrinterPlugin}
  assets: []
  fonts: []
